"""
CADä»£ç ç”Ÿæˆå·¥å…·æ¨¡å—
"""
from SimpleLLMFunc import llm_function, tool
from typing import Optional
import json
from .common import (
    get_config, global_context, print_tool_output, 
    safe_asyncio_run, get_global_sketch_pad
)


@tool(
    name="cad_query_code_generator",
    description="Generate high-quality CAD Query code based on user requirements and context information. Supports SketchPad key input and auto-storage.",
)
def cad_query_code_generator(query: str, store_result: bool = True) -> str:
    """
    Args:
        query: ç”¨æˆ·çš„åŽŸå§‹è¯·æ±‚ï¼Œæˆ–è€…SketchPadçš„keyç”¨äºŽå¼•ç”¨å·²å­˜å‚¨çš„éœ€æ±‚;ä½ ä¹Ÿå¯ä»¥ä½¿ç”¨SketchPadçš„keyæ¥å¼•ç”¨ä¹‹å‰çš„éœ€æ±‚å†…å®¹ï¼Œå¦‚æžœè¿™æ ·ä½ éœ€è¦ä½¿ç”¨`key:`å‰ç¼€æ¥æ ‡è¯†,ä¾‹å¦‚ï¼š`key:1234567890abcdef`
        store_result: æ˜¯å¦è‡ªåŠ¨å°†ç”Ÿæˆçš„ä»£ç å­˜å‚¨åˆ°SketchPad
        
    Returns:
        str: ç”Ÿæˆçš„CAD Queryä»£ç å’ŒSketchPad keyä¿¡æ¯
    """
    
    sketch_pad = get_global_sketch_pad()
    
    # æ£€æŸ¥queryæ˜¯å¦ä¸ºSketchPad key
    if query.startswith("key:"):
        key_to_retrieve = query[4:]  # åŽ»æŽ‰ "key:" å‰ç¼€
        sketch_content = sketch_pad.retrieve(key_to_retrieve)
        if sketch_content is not None:
            actual_query = str(sketch_content)
            print_tool_output(
                title="ðŸ“‹ CADQuery Code Genï¼šä»ŽSketchPadèŽ·å–éœ€æ±‚",
                content=f"Key: {key_to_retrieve}\néœ€æ±‚å†…å®¹: {actual_query[:100]}..."
            )
        else:
            actual_query = query.strip()
            print_tool_output(
                title="ðŸ“‹ CADQuery Code Genï¼šSketchPad keyæœªæ‰¾åˆ°ï¼Œä½¿ç”¨åŽŸå§‹query",
                content=f"å¤„ç†è¯·æ±‚ï¼š {actual_query[:100]}..."
            )
    else:
        actual_query = query.strip()
        print_tool_output(
            title="ðŸ“‹ CADQuery Code Genï¼š ä½¿ç”¨ç”¨æˆ·æä¾›çš„éœ€æ±‚ç”Ÿæˆä»£ç ",
            content=f"å¤„ç†è¯·æ±‚ï¼š {actual_query[:100]}..."
        )
    
    context = global_context.get_formatted_history()[-3:]
    context = json.dumps(context, ensure_ascii=False, indent=2)
    
    result = cad_query_code_generator_impl(actual_query, context)
    
    print_tool_output(
        title="ç”Ÿæˆçš„CAD Queryä»£ç ",
        content=result[:100] + ("..." if len(result) > 100 else ""),
    )
    
    # è‡ªåŠ¨å­˜å‚¨ç”Ÿæˆçš„ä»£ç åˆ°SketchPad
    if store_result:
        import uuid
        code_key = f"code_{uuid.uuid4().hex[:8]}"
        
        async def _store_code():
            return await sketch_pad.store(
                value=result.strip(),
                key=code_key,  # ä½¿ç”¨è‡ªå®šä¹‰key
                tags={"cadquery", "generated_code", "modeling"},
                auto_summarize=True
            )
        
        try:
            actual_key = safe_asyncio_run(_store_code)
            
            print_tool_output(
                title="ðŸ’¾ ä»£ç å·²å­˜å‚¨åˆ°SketchPad",
                content=f"Key: {code_key}\nä»£ç é•¿åº¦: {len(result)} å­—ç¬¦"
            )
            
            return f"""CADä»£ç ç”Ÿæˆå®Œæˆå¹¶å­˜å‚¨åˆ°SketchPad:

ðŸ”‘ SketchPad Key: {code_key}
# Tag: cadquery, generated_code, modeling 
ðŸ“„ ä»£ç å†…å®¹:
```python
{result.strip()}
```

ðŸ’¡ æç¤º: æ‚¨çŽ°åœ¨å¯ä»¥ä½¿ç”¨key "{code_key}" è¿›è¡ŒåŽç»­æ“ä½œ:
- ä½¿ç”¨ file_operations å·¥å…·å°†ä»£ç ä¿å­˜åˆ°æ–‡ä»¶
- ä½¿ç”¨ execute_command å·¥å…·è¿è¡Œä»£ç 
- ä½¿ç”¨ sketch_pad_operations å·¥å…·ç®¡ç†å’Œå¼•ç”¨æ­¤ä»£ç 

å»ºè®®å……åˆ†åˆ©ç”¨SketchPadçš„keyæœºåˆ¶ï¼"""
        
        except Exception as e:
            print_tool_output("âŒ å­˜å‚¨å¤±è´¥", f"Failed to store code: {e}")
            return result.strip()
    
    return result.strip()


@llm_function(
    llm_interface=get_config().CODE_INTERFACE,
    timeout=600,
)
def cad_query_code_generator_impl(
    query: str, context: str
) -> str:  # type: ignore
    """
    Args:
        query: ç”¨æˆ·çš„åŽŸå§‹è¯·æ±‚
        context: ä¸Šä¸‹æ–‡ä¿¡æ¯ï¼ŒåŒ…å«ç”¨æˆ·çš„æ„å›¾ã€æ‰©å±•æ„å›¾å’Œå¯èƒ½çš„å‚è€ƒä»£ç 
        
    Returns:
        str: ç”Ÿæˆçš„CAD Queryä»£ç 
    
    
    # Task:
    You are an expert CAD engineer with access to the Python library CadQuery .
    Your job is to create Python code that generates a 3 D model based on a given description .
    Make sure to include all relevant parts .
    Pay special attention to the orientation of all parts , e . g . , by choosing appropriate workplanes .
    For instance , pick a workplane perpendicular to the ground for sketching the outline of the wheels
    of a toy car .
    Whenever possible , use the default workplanes , i . e . , XY , XZ , and YZ .
    
    # ä¾‹å¦‚ï¼š
    query: æˆ‘æƒ³è¦ä¸€ä¸ªå¸¦æœ‰ç›–å­çš„ç›’å­
    
    return:
    ```python
    import cadquery as cq
    from cadquery import exporters
    from cadquery.func import *
    # -------------------------
    # Parameters
    # -------------------------
    p_outerWidth = 100.0
    p_outerLength = 150.0
    p_outerHeight = 50.0

    p_thickness = 3.0
    p_sideRadius = 10.0
    p_topAndBottomRadius = 2.0

    p_screwpostInset = 12.0
    p_screwpostID = 4.0
    p_screwpostOD = 10.0

    p_boreDiameter = 8.0
    p_boreDepth = 1.0
    p_countersinkDiameter = 0.0
    p_countersinkAngle = 90.0
    p_flipLid = True
    p_lipHeight = 1.0

    # -------------------------
    # Outer shell
    # -------------------------
    oshell = (
        cq.Workplane("XY")
        .rect(p_outerWidth, p_outerLength)
        .extrude(p_outerHeight + p_lipHeight)
        .tag("outer_shell_raw")
    )

    if p_sideRadius > p_topAndBottomRadius:
        oshell = oshell.edges("|Z").fillet(p_sideRadius)
        oshell = oshell.edges("#Z").fillet(p_topAndBottomRadius)
    else:
        oshell = oshell.edges("#Z").fillet(p_topAndBottomRadius)
        oshell = oshell.edges("|Z").fillet(p_sideRadius)

    # -------------------------
    # Inner shell
    # -------------------------
    ishell = (
        oshell.faces("<Z")
        .workplane(p_thickness, True)
        .rect(p_outerWidth - 2 * p_thickness, p_outerLength - 2 * p_thickness)
        .extrude(p_outerHeight - 2 * p_thickness, combine=False)
        .edges("|Z")
        .fillet(p_sideRadius - p_thickness)
        .tag("inner_shell")
    )

    box = oshell.cut(ishell).tag("main_box")

    # -------------------------
    # Screw posts
    # -------------------------
    POSTWIDTH = p_outerWidth - 2.0 * p_screwpostInset
    POSTLENGTH = p_outerLength - 2.0 * p_screwpostInset

    box = (
        box.faces(">Z")
        .workplane(-p_thickness)
        .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)
        .vertices()
        .tag("screw_positions")
        .circle(p_screwpostOD / 2.0)
        .circle(p_screwpostID / 2.0)
        .extrude(-1.0 * (p_outerHeight + p_lipHeight - p_thickness), True)
    )

    # -------------------------
    # Split into lid and bottom
    # -------------------------
    (lid, bottom) = (
        box.faces(">Z")
        .workplane(-p_thickness - p_lipHeight)
        .split(keepTop=True, keepBottom=True)
        .all()
    )

    bottom = bottom - lid

    # Create new lid with inset lip
    lowerLid = lid.translate((0, 0, -p_lipHeight))
    cutlip = (
        lowerLid.cut(bottom)
        .translate((p_outerWidth + p_thickness, 0, p_thickness - p_outerHeight + p_lipHeight))
        .tag("lid_with_lip")
    )

    # -------------------------
    # Screw holes
    # -------------------------
    topOfLidCenters = (
        cutlip.faces(">Z")
        .workplane(centerOption="CenterOfMass")
        .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)
        .vertices()
    )

    if p_boreDiameter > 0 and p_boreDepth > 0:
        topOfLid = topOfLidCenters.cboreHole(
            p_screwpostID, p_boreDiameter, p_boreDepth, 2.0 * p_thickness
        )
    elif p_countersinkDiameter > 0 and p_countersinkAngle > 0:
        topOfLid = topOfLidCenters.cskHole(
            p_screwpostID, p_countersinkDiameter, p_countersinkAngle, 2.0 * p_thickness
        )
    else:
        topOfLid = topOfLidCenters.hole(p_screwpostID, 2.0 * p_thickness)

    if p_flipLid:
        topOfLid = topOfLid.rotateAboutCenter((1, 0, 0), 180)

    del lowerLid
    del lid
    del box
    del oshell
    del ishell

    # -------------------------
    # Final result
    # -------------------------
    result = topOfLid.union(bottom).union(loft)

    # -------------------------
    # Export
    # -------------------------
    exporters.export(result, "fixed_box_with_lid.step")
    exporters.export(result, "fixed_box_with_lid.stl")
    ``` 
    """

