"""
ç»†åŒ–éœ€æ±‚å·¥å…·æ¨¡å—
"""
from SimpleLLMFunc import llm_function, tool
from typing import Optional
import json
from .common import (
    get_config, global_context, print_tool_output, 
    safe_asyncio_run, get_global_sketch_pad
)


@tool(
    name="make_user_query_more_detailed",
    description="You can use this tool to refine and expand the user's requirements. Automatically stores expanded requirements in SketchPad.",
)
def make_user_query_more_detailed(query: str, store_in_sketch_pad: bool = True) -> str:
    """
        Args:
            query: The user's original request, combined with expanding requirements.
            store_in_sketch_pad: Whether to automatically store the expanded query in SketchPad

        Returns:
            str: Detailed user request with SketchPad key information
    """
    
    print_tool_output(
        title="ä½¿ç”¨å·¥å…·ç»†åŒ–ç”¨æˆ·éœ€æ±‚",
        content=f"ç»†åŒ–è¦æ±‚ï¼š {query}",
    )

    context = global_context.get_formatted_history()[-3:]
    context = json.dumps(context, ensure_ascii=False, indent=2)
    
    result = make_user_query_more_detailed_impl(query, context)  # type: ignore[call-arg]

    # å»æ‰å¤´éƒ¨çš„<think></think>æ ‡ç­¾
    if result.startswith("<think>"):
        result = result[len("<think></think>") :]

    print_tool_output(
        title="ç»†åŒ–åçš„ç”¨æˆ·éœ€æ±‚",
        content=result,
    )

    # è‡ªåŠ¨å­˜å‚¨åˆ° SketchPad
    if store_in_sketch_pad:
        import uuid
        sketch_pad = get_global_sketch_pad()
        sketch_key = f"req_{uuid.uuid4().hex[:8]}"
        
        async def _store_detailed_query():
            return await sketch_pad.store(
                value=result.strip(),
                key=sketch_key,  # ä½¿ç”¨è‡ªå®šä¹‰key
                tags={"detailed_query", "requirements", "expanded"},
                auto_summarize=True
            )
        
        try:
            actual_key = safe_asyncio_run(_store_detailed_query)
            
            print_tool_output(
                title="ğŸ’¾ å·²å­˜å‚¨åˆ° SketchPad",
                content=f"Key: {sketch_key}\nè¯¦ç»†éœ€æ±‚å·²ä¿å­˜ï¼Œæ‚¨å¯ä»¥ä½¿ç”¨æ­¤keyåœ¨åç»­å·¥å…·ä¸­å¼•ç”¨"
            )
            
            # è¿”å›åŒ…å«keyä¿¡æ¯çš„ç»“æœ
            return f"""è¯¦ç»†éœ€æ±‚å·²ç”Ÿæˆå¹¶å­˜å‚¨åˆ°SketchPad:

ğŸ”‘ SketchPad Key: {sketch_key}
# Tags: detailed_query, requirements, expanded
ğŸ“‹ è¯¦ç»†éœ€æ±‚å†…å®¹:
{result.strip()}

ğŸ’¡ æç¤º: æ‚¨ç°åœ¨å¯ä»¥ä½¿ç”¨key "{sketch_key}" åœ¨åç»­çš„å·¥å…·æ“ä½œä¸­å¼•ç”¨æ­¤è¯¦ç»†éœ€æ±‚ï¼Œä¾‹å¦‚:
- ä½¿ç”¨ cad_query_code_generator å·¥å…·æ—¶ï¼Œå¯ä»¥ç›´æ¥ä¼ å…¥æ­¤keyä½œä¸ºqueryå‚æ•°
- ä½¿ç”¨ file_operations å·¥å…·å°†éœ€æ±‚ä¿å­˜åˆ°æ–‡ä»¶
- ä½¿ç”¨ sketch_pad_operations å·¥å…·è¿›è¡Œè¿›ä¸€æ­¥çš„å†…å®¹ç®¡ç†

å»ºè®®æ‚¨å……åˆ†åˆ©ç”¨SketchPadçš„keyæœºåˆ¶æ¥æé«˜å·¥ä½œæ•ˆç‡ï¼"""
        
        except Exception as e:
            print_tool_output("âŒ å­˜å‚¨å¤±è´¥", f"Failed to store in SketchPad: {e}")
            return result.strip()  # è¿”å›åŸå§‹ç»“æœ
    
    return result.strip()


@llm_function(
    llm_interface=get_config().QUICK_INTERFACE,
    timeout=600
)
def make_user_query_more_detailed_impl(query: str, context: str) -> str:  # type: ignore
    """       
        ### Task:
        - You need to refine and expand the user's requirements.

        - user requirements will be contained in the `query` parameter.

        - Pay Attention that we are going to write CADQuery Code, so the requirements should be detailed with CADQuery API

        ### Example:
        - query: I want a gear
        - You can refine it to:
        '''
        # ğŸ› ï¸ é½¿è½®å»ºæ¨¡è§„

        ## ä¸€ã€é½¿è½®å‚æ•°ï¼ˆGear Parametersï¼‰

            | å‚æ•°           | å«ä¹‰                          | å€¼       |
            | ------------ | --------------------------- | ------- |
            | `z`          | é½¿æ•°ï¼ˆNumber of Teethï¼‰         | 18      |
            | `m`          | æ¨¡æ•°ï¼ˆModuleï¼‰                  | 2.0 mm  |
            | `Î±`          | å‹åŠ›è§’ï¼ˆPressure Angleï¼‰         | 20Â°     |
            | `t`          | é½¿è½®åšåº¦ï¼ˆGear Thicknessï¼‰        | 10.0 mm |
            | `r_hole`     | ä¸­å¿ƒå­”åŠå¾„ï¼ˆCenter Hole Radiusï¼‰   | 10.0 mm |
            | `slot_width` | åŠæœˆæ§½å®½åº¦ï¼ˆHalf-moon Slot Widthï¼‰ | 5.0 mm  |

            ---

        ## äºŒã€æ•´ä½“ç»“æ„æ‹†è§£ä¸å»ºæ¨¡æ­¥éª¤

        ### Part 1: é½¿è½®åŸºä½“ï¼ˆGear Base Bodyï¼‰

        #### ğŸ“ Step 1: ç”Ÿæˆé½¿è½®å¤–åœ† Sketch

            * **å‡ ä½•å®šä¹‰**ï¼š

            * å¤–åœ†åŠå¾„ $r_{\text{gear}} = \frac{m \\cdot z}{2} = \frac{2.0 \\cdot 18}{2} = 18.0\\, \text{mm}$

            * **çº¿æ¡†ï¼ˆWireï¼‰åˆ›å»º**ï¼š

            * ç»˜åˆ¶ä¸€ä¸ªåœ†å¿ƒä¸ºåŸç‚¹ã€åŠå¾„ä¸º 18.0mm çš„ 2D Circleï¼ˆç§°ä¸º `outer_circle_wire`ï¼‰

            * **é¢ï¼ˆFaceï¼‰ç”Ÿæˆ**ï¼š

            * å°† `outer_circle_wire` å°é—­æˆä¸€ä¸ª `outer_face`ï¼ˆå°é—­é¢ï¼‰

            * **å®ä½“ï¼ˆBodyï¼‰ç”Ÿæˆ**ï¼š

            * å°† `outer_face` ä»¥åšåº¦ 10.0mm æ²¿ Z è½´æ‹‰ä¼¸æˆå®ä½“ï¼Œå¾—åˆ°åœ†æŸ±ä½“ `gear_base_body`

            ---

        ### Part 2: é½¿è½®é½¿å½¢ï¼ˆTooth Generationï¼‰

        #### ğŸ“ Step 2: å•é½¿è½®å»“çº¿ç”Ÿæˆï¼ˆInvolute Profileï¼‰

            * **è®¡ç®—åŸºåœ†åŠå¾„**ï¼š

            $$
            r_b = r_{\text{gear}} \\cdot \\cos(\alpha) = 18.0 \\cdot \\cos(20Â°) â‰ˆ 16.91 \text{ mm}
            $$

            * **ä½¿ç”¨æ¸å¼€çº¿æ–¹ç¨‹æ„é€ é½¿å»“**ï¼š

            * ç”¨æåæ ‡å®šä¹‰æ¸å¼€çº¿ï¼š

                $$
                x(\theta) = r_b(\\cos\theta + \theta\\sin\theta), \\quad y(\theta) = r_b(\\sin\theta - \theta\\cos\theta)
                $$
            * é€‰å–åˆé€‚çš„ $\theta$ èŒƒå›´ï¼ˆä¾‹å¦‚ä» 0 åˆ° $\theta_{\text{max}}$ï¼Œå¯é€šè¿‡é½¿é¡¶åœ†æˆªè·ç¡®å®šï¼‰

            * **æ„é€ é½¿å½¢è½®å»“çº¿ï¼ˆTooth Wireï¼‰**ï¼š

            * å·¦å³æ¸å¼€çº¿å„ä¸€æ¡ï¼Œé¡¶éƒ¨ç”¨åœ†å¼§æˆ–ç›´çº¿é—­åˆ
            * å°é—­ä¸ºä¸€ä¸ªå°é—­è½®å»“ï¼ˆé—­åˆ wireï¼‰ï¼Œç§°ä¸º `tooth_wire`

        #### ğŸ“¦ Step 3: æ‹‰ä¼¸é½¿å»“å½¢æˆå•é½¿å®ä½“

            * å°† `tooth_wire` æ‹‰ä¼¸ä¸ºåšåº¦ `t`ï¼Œç”Ÿæˆ `tooth_solid`ï¼ˆå•é½¿å®ä½“ï¼‰

        #### ğŸ” Step 4: å¤åˆ¶æ—‹è½¬æˆé½¿è½®é½¿é˜µåˆ—

            * **é˜µåˆ—å¤åˆ¶**ï¼š

            * æ—‹è½¬å¤åˆ¶ `tooth_solid` å…± 18 ä¸ªï¼ˆ360Â° / 18 = 20Â°ï¼‰ï¼Œå¾—åˆ°å¤šä¸ªé½¿å®ä½“é›†åˆ `teeth_array`

        #### â• Step 5: å¸ƒå°”å¹¶é›†åˆå¹¶é½¿ä¸åŸºä½“

            * å¯¹æ‰€æœ‰é½¿å®ä½“å’Œ `gear_base_body` è¿›è¡Œå¸ƒå°”å¹¶é›†è¿ç®—ï¼Œç»“æœå‘½åä¸º `gear_with_teeth`

            ---

        ### Part 3: ä¸­å¿ƒå­” + åŠæœˆæ§½ï¼ˆCenter Hole & Slotï¼‰

        #### âš™ï¸ Step 6: ä¸­å¿ƒå­” Sketch

            * **ç»˜åˆ¶ä¸­å¿ƒå­”åœ†çº¿æ¡†**ï¼š

            * åŠå¾„ä¸º `r_hole = 10.0mm` çš„åœ† `center_hole_wire`

            * **ç”Ÿæˆå­”ä½“**ï¼š

            * æ‹‰ä¼¸ `center_hole_wire` ä¸ºåšåº¦ `t` çš„å®ä½“ `center_hole_cylinder`

        #### â– Step 7: å¸ƒå°”å‡å»ä¸­å¿ƒå­”

            * `gear_with_hole = gear_with_teeth - center_hole_cylinder`

        #### ğŸŒ“ Step 8: åŠæœˆæ§½ï¼ˆHalf-moon Slotï¼‰å¯é€‰

            * **æ„é€ åŠæœˆæ§½ sketch**ï¼ˆå¯é€‰ï¼‰ï¼š

            * å¯ä»¥åœ¨ä¸­å¿ƒå­”è¾¹ç¼˜åˆ‡é™¤ä¸€ä¸ªå®½ä¸º `slot_width` çš„æ‰‡å½¢åŒºåŸŸ
            * æˆ–è€…ï¼š

                * ç”»ä¸€ä¸ªåœ†å¼§å®½ 5.0mmï¼Œé™„ç€äºå­”è¾¹
                * å°é—­åŒºåŸŸåæ‹‰ä¼¸å½¢æˆå®ä½“ `slot_body`

            * **å¸ƒå°”å‡å»åŠæœˆæ§½**ï¼š

            * `gear_final = gear_with_hole - slot_body`ï¼ˆå¦‚æœ‰è¯¥æ§½ï¼‰

        ---

        ## å››ã€å¯¼å‡ºæ¨¡å‹

        #### ğŸ“ Step 9: å¯¼å‡º STEP æ–‡ä»¶

            ```python
            gear_final.exportStep("gear_18_teeth.step")
            ```
        ---

        ## å…­ã€å»ºæ¨¡æ ¸å¿ƒè¦ç‚¹æç¤º

        1. **æ¸å¼€çº¿ç”Ÿæˆ**ï¼š
        2. **Boolean æ“ä½œé¡ºåº**ï¼š
           * å…ˆ union æ‰€æœ‰é½¿ â†’ å† subtract center hole â†’ å† subtract slotï¼ˆé¡ºåºä¼šå½±å“æ‹“æ‰‘æ­£ç¡®æ€§ï¼‰
        3. **é—­åˆ Wire æ£€æŸ¥**ï¼š
           * é½¿å½¢å¿…é¡»ä¸ºå®Œæ•´å°é—­åŒºåŸŸï¼Œæ‰èƒ½æ‹‰ä¼¸ä¸º Face å’Œ Solid
        4. **åšåº¦ç»Ÿä¸€**ï¼š
           * æ‰€æœ‰ extrusion éƒ½ç”¨åŒä¸€åšåº¦ `t` ä¿è¯å¸ƒå°”æ“ä½œä¸ä¼šå¤±è´¥

        è¯·åŠ¡å¿…ä½¿ç”¨æ­£ç¡®çš„CADQuery APIå’Œå‡ ä½•æ¦‚å¿µæ¥å®ç°ä»¥ä¸Šæ­¥éª¤ï¼Œç¡®ä¿ç”Ÿæˆçš„é½¿è½®ç¬¦åˆè®¾è®¡è¦æ±‚ã€‚
        '''
    """
